version: '3.7'

services:
  spring:
    container_name: spring-compose
    build:
      context: compose-spring
      dockerfile: compose-spring/Dockerfile
    ports:
      - 5551:8080
    volumes:
      - ./build/libs:/deploy